// ================ WARNING! ================
// DO NOT #INCLUDE THIS FILE IN YOUR PROGRAM!
// IT IS INTENDED FOR IMPLEMENTATION USE ONLY.

#ifndef DYNAMO_SOUND_SYSTEM_DYNAMO_IMPL_H
#define DYNAMO_SOUND_SYSTEM_DYNAMO_IMPL_H

#include "dynamo.h"

#endif
